server: started deno ts server

diff --git a/server/mongodb b/server/mongodb
--- a/server/mongodb
+++ b/server/mongodb
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
 # $1 = command to run, commands:
-# - start: start Redis container
-# - status: get status of container, outputs "running" if Redis server is running,
-#           "stopped" if the Redis container is stopped but still exists, and
-#           "not found" if the Redis container does not exist.
+# - start: start Mongo container
+# - status: get status of container, outputs "running" if Mongo server is running,
+#           "stopped" if the Mongo container is stopped but still exists, and
+#           "not found" if the Mongo container does not exist.
 if [ -z "$CONTAINER_CLI" ]; then
     CONTAINER_CLI="sudo podman"
 fi
 
-container_name=dev-video-sync-redis
-container_tag="redis:latest"
+container_name=dev-video-sync-mongo
+container_tag="mongo:latest"
 
 function die() {
-    echo "redis: $@" >&2
+    echo "mongo: $@" >&2
     exit 1
 }
 
@@ -42,7 +42,7 @@ case "$1" in
 		  stopped)
 			 $CONTAINER_CLI rm "$container_name"
 			 ;;
-		  *) die "Cannot stop and remove redis if not running" ;;
+		  *) die "Cannot stop and remove mongo if not running" ;;
 	   esac
 	   ;;
     logs)
@@ -50,12 +50,12 @@ case "$1" in
 		  running)
 			 $CONTAINER_CLI logs -f "$container_name"
 			 ;;
-		  *) die "Cannot get logs if Redis is not running" ;;
+		  *) die "Cannot get logs if Mongo is not running" ;;
 	   esac
 	   ;;
     cli)
 	   shift
-	   $CONTAINER_CLI run -it --rm --net host "$container_tag" redis-cli $@
+	   $CONTAINER_CLI run -it --rm --net host "$container_tag" mongo $@
 	   ;;
     *)
 	   die "first argument must be \"start\", \"status\", \"stop\", \"logs\", \"cli\""
